name: Publishing
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: gradle build

      - name: Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./build/libs/Bindea-${{ github.event.inputs.version }}.jar
          asset_name: Bindea-${{ github.event.inputs.version }}.jar
          asset_content_type: application/jar

      - name: Publish on JetBrain's Marketplace
        if: "false"
        continue-on-error: true
        run: gradle publishPlugin
