name: Publishing
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          echo ${ secrets.GRADLE_PROPERTIES }
          echo ${GRADLE_PROPERTIES} >> gradle.properties
          cat ~/.gradle/gradle.properties

      - name: Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Retrieve tag version
        run: |
          $version = ${github_ref/refs.tags./}
          echo $version
          echo "::set-env name=version::$version"

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./Bindea.jar
          asset_name: Bindea-${{ env.version }} .jar
          asset_content_type: application/jar

      - name: Publish on JetBrain's Marketplace
        if: "false"
        continue-on-error: true
        run: gradle publishPlugin
